package infbook;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Henrik
 */
public class BytLosenord extends javax.swing.JFrame {

    private Connection connection;
    private String personnummer;

    public BytLosenord(Connection connection, String personnummer) {
        initComponents();
        this.setResizable(false);
        this.connection = connection;
        this.personnummer = personnummer;
        lblConfirmation.setVisible(false);
        lblGammaltLosenord.setVisible(false);
        pwfGammaltL.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBytLosenord = new javax.swing.JButton();
        pwfNyttL = new javax.swing.JPasswordField();
        pwfGammaltL = new javax.swing.JPasswordField();
        lblGammaltLosenord = new javax.swing.JLabel();
        lblNyttLosenord = new javax.swing.JLabel();
        lblConfirmation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnBytLosenord.setText("Byt Lösenord");
        btnBytLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBytLosenordActionPerformed(evt);
            }
        });

        lblGammaltLosenord.setText("Gammalt lösenord");

        lblNyttLosenord.setText("Nytt losenord");

        lblConfirmation.setText("Lösenordet har ändrats");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblConfirmation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGammaltLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNyttLosenord)
                    .addComponent(pwfGammaltL)
                    .addComponent(pwfNyttL)
                    .addComponent(btnBytLosenord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(lblGammaltLosenord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwfGammaltL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblNyttLosenord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwfNyttL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnBytLosenord)
                .addGap(30, 30, 30)
                .addComponent(lblConfirmation)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBytLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBytLosenordActionPerformed

        //String angivetGammaltLosenord = pwfGammaltL.getText();
        String angivetNyttLosenord = pwfNyttL.getText();

        try {
            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT LOSENORD FROM ANVANDARE WHERE PNR ='" + personnummer+"'");
            rs.next();
            String gammaltLosenord = rs.getString("LOSENORD");
//
            if (gammaltLosenord.equals(angivetNyttLosenord)) {
                JOptionPane.showMessageDialog(null, "Det nya lösenordet får inte vara samma som det gamla");
            }
//
//            else if (angivetGammaltLosenord.equals(gammaltLosenord)) {

                Statement stmt2 = connection.createStatement();
                stmt2.executeUpdate("UPDATE ANVANDARE SET LOSENORD ='" + angivetNyttLosenord + "' WHERE PNR ='" + personnummer+"'");
                lblConfirmation.setVisible(true);

//            } else {
//
//                JOptionPane.showMessageDialog(null, "Ditt gamla lösenord angavs inte korrekt");
//
//            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btnBytLosenordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBytLosenord;
    private javax.swing.JLabel lblConfirmation;
    private javax.swing.JLabel lblGammaltLosenord;
    private javax.swing.JLabel lblNyttLosenord;
    private javax.swing.JPasswordField pwfGammaltL;
    private javax.swing.JPasswordField pwfNyttL;
    // End of variables declaration//GEN-END:variables
}
