/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infbook;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomasz
 */
public class HanteraAnvandare extends javax.swing.JFrame {

    private Connection connection;
    private DefaultListModel lista;
    private String status;

    /**
     * Creates new form HanteraAnvandare
     */
    public HanteraAnvandare(Connection connection, String status) {
        this.connection = connection;
        lista = new DefaultListModel();
        initComponents();
        this.setResizable(false);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        this.status = status;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSokAnvandare = new javax.swing.JTextField();
        lblSokAnvandare = new javax.swing.JLabel();
        btnSok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstResultat = new javax.swing.JList();
        btnSkapaAnvandare = new javax.swing.JButton();
        btnAndraAnvandare = new javax.swing.JButton();
        lblResultat = new javax.swing.JLabel();
        btnRaderaAnvandare = new javax.swing.JButton();
        lblNotis = new javax.swing.JLabel();
        btnAktivera = new javax.swing.JButton();
        btnInaktivera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSokAnvandare.setText("Sök användare");

        btnSok.setText("Sök");
        btnSok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstResultat);

        btnSkapaAnvandare.setText("Skapa användare");
        btnSkapaAnvandare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaAnvandareActionPerformed(evt);
            }
        });

        btnAndraAnvandare.setText("Ändra markerad användare");
        btnAndraAnvandare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraAnvandareActionPerformed(evt);
            }
        });

        lblResultat.setText("Resultat");

        btnRaderaAnvandare.setText("Radera markerad användare");
        btnRaderaAnvandare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaderaAnvandareActionPerformed(evt);
            }
        });

        btnAktivera.setText("Återaktivera markerad användare");
        btnAktivera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAktiveraActionPerformed(evt);
            }
        });

        btnInaktivera.setText("Inaktivera markerad användare");
        btnInaktivera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInaktiveraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNotis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSokAnvandare)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSokAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(btnSok))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnSkapaAnvandare)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblResultat)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInaktivera, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(btnAndraAnvandare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRaderaAnvandare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAktivera, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSokAnvandare)
                    .addComponent(lblResultat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSokAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSok))
                        .addGap(31, 31, 31)
                        .addComponent(btnSkapaAnvandare))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnAndraAnvandare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInaktivera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRaderaAnvandare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAktivera)
                    .addComponent(lblNotis, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSkapaAnvandareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaAnvandareActionPerformed
        new SkapaAnvandare(connection, status).setVisible(true);
    }//GEN-LAST:event_btnSkapaAnvandareActionPerformed

    private void btnSokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokActionPerformed

        {
            lista.removeAllElements();
            String soktAnvandare = txtSokAnvandare.getText();
            soktAnvandare = Validering.makeFirstLetterUpperCase(txtSokAnvandare.getText());

            try {

                Statement placeholder = connection.createStatement();
                ResultSet rs = placeholder.executeQuery("SELECT * FROM ANVANDARE");

                if (status.equals("CA")) { //Om du är CA
                    Statement stmt = connection.createStatement();
                    rs = stmt.executeQuery("SELECT PNR, FORNAMN, EFTERNAMN FROM ANVANDARE WHERE FORNAMN LIKE '" + soktAnvandare + "%'");
                }

                if (status.equals("FA")) { //Om du är FA
                    Statement stmt = connection.createStatement();
                    rs = stmt.executeQuery("SELECT PNR, FORNAMN, EFTERNAMN FROM ANVANDARE WHERE FORNAMN LIKE '" + soktAnvandare + "%' AND STATUS LIKE 'F%'");
                } else if (status.equals("UA")) { //Om du är UA
                    Statement stmt = connection.createStatement();
                    rs = stmt.executeQuery("SELECT PNR, FORNAMN, EFTERNAMN FROM ANVANDARE WHERE FORNAMN LIKE '" + soktAnvandare + "%' AND STATUS LIKE 'U%'");
                }

                while (rs.next()) {
                    String personnummer = rs.getString("PNR");
                    String fornamn = rs.getString("FORNAMN");
                    String efternamn = rs.getString("EFTERNAMN");

                    lista.addElement(personnummer + " " + fornamn + " " + efternamn + "\n");
                    lstResultat.setModel(lista);
                }

            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }


    }//GEN-LAST:event_btnSokActionPerformed

    private void btnAndraAnvandareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraAnvandareActionPerformed
        if (Validering.isJListTomt(lstResultat)) {
            String information = lstResultat.getSelectedValue().toString();
            String personnummer = information.substring(0, information.indexOf(" "));

            new AndraProfil(connection, personnummer, status).setVisible(true);
        }
    }//GEN-LAST:event_btnAndraAnvandareActionPerformed

    private void btnRaderaAnvandareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaderaAnvandareActionPerformed
        if (Validering.isJListTomt(lstResultat)) {
            String information = lstResultat.getSelectedValue().toString();
            String personnummer = information.substring(0, information.indexOf(" "));
            System.out.println(personnummer);
            try {

                Statement stmt = connection.createStatement();

                try { //1

                    stmt.executeUpdate("DELETE FROM MOTELSEKALLELSE WHERE PNR ='" + personnummer+"'");

                } catch (SQLException e) {
                }

                try {//2

                    stmt.executeUpdate("DELETE FROM ANVANDARE_KOMMENTERA_INLAGG WHERE ANVANDARE ='" + personnummer+"'");

                } catch (SQLException e) {
                }

                try {//3

                    stmt.executeUpdate("DELETE FROM ANVANDARE_SUPERKATEGORI WHERE ANVANDARE ='" + personnummer+"'");

                } catch (SQLException e) {
                }

                try {//4

                    stmt.executeUpdate("DELETE FROM INLAGG WHERE ANVANDARE ='" + personnummer+"'");

                } catch (SQLException e) {
                }

                try {//5

                    stmt.executeUpdate("DELETE FROM MOTELSEKALLELSE_ANV_SVAR WHERE ANVANDARE ='" + personnummer+"'");

                } catch (SQLException e) {
                }

                try { //6

                    stmt.executeUpdate("DELETE FROM MOTE_ANVANDARE WHERE ANVANDARE ='" + personnummer+"'");

                } catch (SQLException e) {
                }

                try { //7

                    stmt.executeUpdate("DELETE FROM FILER WHERE INLAGG =(SELECT INLAGGSID FROM INLAGG WHERE ANVANDARE ='" + personnummer + "')");

                } catch (SQLException e) {
                }

                try { //8
                    stmt.executeUpdate("UPDATE KOMMENTAR SET INLAGG = NULL WHERE ANVANDARE ='" + personnummer+"'");
                    stmt.executeUpdate("DELETE FROM KOMMENTAR WHERE ANVANDARE='" + personnummer+"'");

                } catch (SQLException e) {
                }

                stmt.executeUpdate("DELETE FROM ANVANDARE WHERE PNR ='" + personnummer+"'");
                lblNotis.setText("Användaren borttagen");
                //JOptionPane.showMessageDialog(null, "Användaren har tagits bort");

            } catch (SQLException e) {

                JOptionPane.showMessageDialog(null, "Något gick fel, användaren kunde inte raderas");
            }
        }
    }//GEN-LAST:event_btnRaderaAnvandareActionPerformed

    private void btnInaktiveraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInaktiveraActionPerformed
        if (Validering.isJListTomt(lstResultat)) {
            String information = lstResultat.getSelectedValue().toString();
            String personnummer = information.substring(0, information.indexOf(" "));
            
            try{
            Statement stmt = connection.createStatement();
            stmt.executeUpdate("UPDATE ANVANDARE SET INAKTIVERAD ='JA' WHERE PNR='"+personnummer+"'");
            lblNotis.setText("Användarkontot är nu inaktiverat");
            
            }
            
            catch(SQLException e){System.out.println(e.getMessage());}
            
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_btnInaktiveraActionPerformed

    private void btnAktiveraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAktiveraActionPerformed
                if (Validering.isJListTomt(lstResultat)) {
            String information = lstResultat.getSelectedValue().toString();
            String personnummer = information.substring(0, information.indexOf(" "));
            
            try{
            Statement stmt = connection.createStatement();
            stmt.executeUpdate("UPDATE ANVANDARE SET INAKTIVERAD =null WHERE PNR='"+personnummer+"'");
            lblNotis.setText("Användarkontot är nu återaktiverat");
            
            }
            
            catch(SQLException e){System.out.println(e.getMessage());}
            
        }

    }//GEN-LAST:event_btnAktiveraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAktivera;
    private javax.swing.JButton btnAndraAnvandare;
    private javax.swing.JButton btnInaktivera;
    private javax.swing.JButton btnRaderaAnvandare;
    private javax.swing.JButton btnSkapaAnvandare;
    private javax.swing.JButton btnSok;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNotis;
    private javax.swing.JLabel lblResultat;
    private javax.swing.JLabel lblSokAnvandare;
    private javax.swing.JList lstResultat;
    private javax.swing.JTextField txtSokAnvandare;
    // End of variables declaration//GEN-END:variables
}
