/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infbook;

import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Henrik
 */
public class Profil extends javax.swing.JFrame {

    private Connection connection;

    /**
     * Creates new form Profil
     */
    public Profil(Connection connection, String angivetAnv) {
        initComponents();
        this.connection = connection;
        jlabelPnr.setText(angivetAnv);
        try {

            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT FORNAMN FROM ANVANDARE WHERE PNR=" + angivetAnv);
            rs.next();
            String fornamn = rs.getString("FORNAMN");
            lblFornamnDB.setText(fornamn);

            Statement stmt2 = connection.createStatement();
            ResultSet rs2 = stmt2.executeQuery("SELECT EFTERNAMN FROM ANVANDARE WHERE PNR=" + angivetAnv);
            rs2.next();
            String efternamn = rs2.getString("EFTERNAMN");
            lblEfternamnDB.setText(efternamn);

            Statement stmt3 = connection.createStatement();
            ResultSet rs3 = stmt3.executeQuery("SELECT EMAIL FROM ANVANDARE WHERE PNR=" + angivetAnv);
            rs3.next();
            String email = rs3.getString("EMAIL");
            lblEpostDB.setText(email);

            Statement stmt4 = connection.createStatement();
            ResultSet rs4 = stmt4.executeQuery("SELECT MOBILNMR FROM ANVANDARE WHERE PNR=" + angivetAnv);
            rs4.next();
            String mobilnmr = rs4.getString("MOBILNMR");
            lblTlfnrDB.setText(mobilnmr);

            Statement stmt5 = connection.createStatement();
            ResultSet rs5 = stmt5.executeQuery("SELECT RUMSNMR FROM ANVANDARE WHERE PNR=" + angivetAnv);
            rs5.next();
            String rumsnmr = rs5.getString("RUMSNMR");
            lblRumsnrDB.setText(rumsnmr);

            Statement stmt6 = connection.createStatement();
            ResultSet rs6 = stmt6.executeQuery("SELECT STATUS FROM ANVANDARE WHERE PNR=" + angivetAnv);
            rs6.next();
            String status = rs6.getString("STATUS");
            lblAnvandarstatusDB.setText(status);
            
            Statement stmt7 = connection.createStatement();
            ResultSet rs7 = stmt7.executeQuery("SELECT PROFILBILD FROM ANVANDARE WHERE PNR=" + angivetAnv);
            rs7.next();
             byte[] img = rs7.getBytes("PROFILBILD");
             
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImg = im.getScaledInstance(lblProfilBildDB.getWidth(), lblProfilBildDB.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImg);
                lblProfilBildDB.setIcon(newImage);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFornamn = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblAnvandarstatus = new javax.swing.JLabel();
        lblRumsnummer = new javax.swing.JLabel();
        lblMobil = new javax.swing.JLabel();
        btnRedigeraInfo = new javax.swing.JButton();
        lblFornamnDB = new javax.swing.JLabel();
        lblEfternamnDB = new javax.swing.JLabel();
        lblAnvandarstatusDB = new javax.swing.JLabel();
        lblTlfnrDB = new javax.swing.JLabel();
        lblEpostDB = new javax.swing.JLabel();
        lblRumsnrDB = new javax.swing.JLabel();
        lblProfilBildDB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlabelPnr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFornamn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFornamn.setText("Förnamn");

        lblEfternamn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEfternamn.setText("Efternamn");

        lblEpost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEpost.setText("E-post");

        lblAnvandarstatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAnvandarstatus.setText("Användarstatus");

        lblRumsnummer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRumsnummer.setText("Rumsnummer");

        lblMobil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMobil.setText("Telefonnummer");

        btnRedigeraInfo.setText("Redigera information");

        lblFornamnDB.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        lblEfternamnDB.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        lblAnvandarstatusDB.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        lblTlfnrDB.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        lblEpostDB.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        lblRumsnrDB.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Personnummer");

        jlabelPnr.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProfilBildDB, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblRumsnrDB, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblMobil, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(lblRumsnummer)
                                    .addComponent(lblTlfnrDB, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAnvandarstatus)
                                            .addComponent(lblAnvandarstatusDB, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblEpost))
                                        .addGap(0, 77, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEpostDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap())))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRedigeraInfo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(jlabelPnr, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEfternamn)
                                    .addComponent(lblFornamn))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEfternamnDB, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFornamnDB, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRedigeraInfo)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMobil)
                            .addComponent(lblEpost))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTlfnrDB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEpostDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRumsnummer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRumsnrDB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblAnvandarstatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAnvandarstatusDB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblProfilBildDB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFornamnDB, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFornamn))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEfternamn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEfternamnDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabelPnr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRedigeraInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlabelPnr;
    private javax.swing.JLabel lblAnvandarstatus;
    private javax.swing.JLabel lblAnvandarstatusDB;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblEfternamnDB;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblEpostDB;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblFornamnDB;
    private javax.swing.JLabel lblMobil;
    private javax.swing.JLabel lblProfilBildDB;
    private javax.swing.JLabel lblRumsnrDB;
    private javax.swing.JLabel lblRumsnummer;
    private javax.swing.JLabel lblTlfnrDB;
    // End of variables declaration//GEN-END:variables
}
