/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infbook;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author meeraj
 */
public class SkapaSubkategori extends javax.swing.JFrame {
    private Connection connection; 

    /**
     * Creates new form SkapaSubkategorier
     */
    public SkapaSubkategori(Connection connection) {
        initComponents();
        this.connection = connection;
        fyllComboBoxSuperkategori();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbValjSupKat = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtfalt = new javax.swing.JTextField();
        lblKategoriNamn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbValjSupKat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbValjSupKatActionPerformed(evt);
            }
        });

        jButton1.setText("SkapaSubkategori");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Välj super kategori");

        txtfalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfaltActionPerformed(evt);
            }
        });

        lblKategoriNamn.setText("Namn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton1)
                            .addComponent(cmbValjSupKat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblKategoriNamn)))
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtfalt, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbValjSupKat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addGap(11, 11, 11)
                .addComponent(lblKategoriNamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbValjSupKatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbValjSupKatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbValjSupKatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String valdsuperkat = String.valueOf(cmbValjSupKat.getSelectedItem());
        String skapaSubkategori = txtfalt.getText();
        
        try { 
            Statement stmt = connection.createStatement();
            
            ResultSet rs = stmt.executeQuery("SELECT SUPERKATEGORIID FROM SUPERKATEGORI WHERE SKNAMN ='" + valdsuperkat + "'");
            rs.next();
            
            int superkategoriid = rs.getInt("SUPERKATEGORIID");
            
            Statement stmtTal = connection.createStatement();
            
            stmtTal.execute("SELECT MAX (SUBKATEGORIID) FROM SUBKATEGORI");
            ResultSet rsTal = stmtTal.getResultSet();
            
            if (rsTal.next()) {
                int hogstaVarde = rsTal.getInt(1);
                int nyaVardet = hogstaVarde + 1;
                System.out.println(hogstaVarde);

                PreparedStatement ps = connection.prepareStatement("insert into SUBKATEGORI(SUBKATEGORIID,SKNAMN,SUPERKATEGORI) values(?,?,?)");
                ps.setInt(1, nyaVardet);
                ps.setString(2, skapaSubkategori);
                ps.setInt(3, superkategoriid);
                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Kategorin har skapats!");
            
       } 
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

     private void fyllComboBoxSuperkategori() {
        Statement stmt;
        try {
            stmt = connection.createStatement();

            ResultSet rs = stmt.executeQuery("SELECT SKNAMN FROM SUPERKATEGORI");

            while (rs.next()) {

                cmbValjSupKat.addItem(rs.getString("SKNAMN"));
                //cmbSuperkategori.addItem("SKNAMN");

            }
        } catch (SQLException ex) {
            Logger.getLogger(SkapaInlagg.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void txtfaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfaltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfaltActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbValjSupKat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblKategoriNamn;
    private javax.swing.JTextField txtfalt;
    // End of variables declaration//GEN-END:variables

}
