/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infbook;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomasz
 */
public class SkapaSuperKategori extends javax.swing.JFrame {

    private Connection connection;

    /**
     * Creates new form SkapaSuperKategori
     */
    public SkapaSuperKategori(Connection connection) {
        initComponents();
        this.setResizable(false);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        this.connection = connection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblOmrade = new javax.swing.JLabel();
        lblKategoriNamn = new javax.swing.JLabel();
        txtKategoriNamn = new javax.swing.JTextField();
        btnSkapaOverkategori = new javax.swing.JButton();
        cmbOmrade = new javax.swing.JComboBox();
        lblNotis = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblOmrade.setText("Välj område");

        lblKategoriNamn.setText("Namn");

        btnSkapaOverkategori.setText("Skapa överkategori");
        btnSkapaOverkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaOverkategoriActionPerformed(evt);
            }
        });

        cmbOmrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Utbildning", "Forskning" }));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/infbook.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOmrade)
                            .addComponent(lblKategoriNamn)
                            .addComponent(txtKategoriNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(cmbOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblNotis, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSkapaOverkategori))))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(lblOmrade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblKategoriNamn)
                .addGap(18, 18, 18)
                .addComponent(txtKategoriNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnSkapaOverkategori)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNotis, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSkapaOverkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaOverkategoriActionPerformed
        if (Validering.isTextFältTomt(txtKategoriNamn)
                && Validering.isString(txtKategoriNamn)) {
            String valtOmrade = String.valueOf(cmbOmrade.getSelectedItem());
            String kategoriNamn = txtKategoriNamn.getText();

            try {
                Statement stmt = connection.createStatement();

                ResultSet rs = stmt.executeQuery("SELECT KATEGORIID FROM KATEGORI WHERE KATEGORINAMN='" + valtOmrade + "'");
                rs.next();

                int kategoriID = rs.getInt("KATEGORIID");

                Statement stmtTal = connection.createStatement();

                stmtTal.execute("SELECT MAX(SUPERKATEGORIID) FROM SUPERKATEGORI");
                ResultSet rsTal = stmtTal.getResultSet();

                if (rsTal.next()) {
                    int hogstaVarde = rsTal.getInt(1);
                    int nyaVardet = hogstaVarde + 1;
                    System.out.println(hogstaVarde);

                    PreparedStatement ps = connection.prepareStatement("insert into SUPERKATEGORI(SUPERKATEGORIID,SKNAMN,KATEGORI) values(?,?,?)");
                    ps.setInt(1, nyaVardet);
                    ps.setString(2, kategoriNamn);
                    ps.setInt(3, kategoriID);
                    ps.executeUpdate();

                    //JOptionPane.showMessageDialog(null, "Kategorin har skapats!");
                    lblNotis.setText("Kategorin har skapats!");
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }


    }//GEN-LAST:event_btnSkapaOverkategoriActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSkapaOverkategori;
    private javax.swing.JComboBox cmbOmrade;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKategoriNamn;
    private javax.swing.JLabel lblNotis;
    private javax.swing.JLabel lblOmrade;
    private javax.swing.JTextField txtKategoriNamn;
    // End of variables declaration//GEN-END:variables
}
